"""Mock tool implementations used by AgentXplain agent."""

from __future__ import annotations

import ast
import contextlib
import io
from dataclasses import dataclass
from typing import Any, Dict


@dataclass
class ToolResult:
    """Container for a tool execution result.

    Args:
        tool: Name of tool executed.
        args: Arguments passed to the tool.
        output: String output generated by the tool.
    """

    tool: str
    args: Dict[str, Any]
    output: str


def web_search(query: str) -> str:
    """Return a placeholder web search result.

    Args:
        query: Query string to search.

    Returns:
        Placeholder result string.

    Raises:
        ValueError: If query is empty.
    """
    if not query.strip():
        raise ValueError("query must be non-empty")
    return f"[Search result for: {query}]"


def _validate_expression(expression: str) -> None:
    """Validate arithmetic expression safety.

    Args:
        expression: Candidate arithmetic expression.

    Returns:
        None.

    Raises:
        ValueError: If expression contains unsupported syntax.
    """
    allowed_nodes = {
        ast.Expression,
        ast.BinOp,
        ast.UnaryOp,
        ast.Num,
        ast.Constant,
        ast.Add,
        ast.Sub,
        ast.Mult,
        ast.Div,
        ast.FloorDiv,
        ast.Mod,
        ast.Pow,
        ast.USub,
        ast.UAdd,
        ast.Load,
        ast.Tuple,
    }
    tree = ast.parse(expression, mode="eval")
    for node in ast.walk(tree):
        if type(node) not in allowed_nodes:
            raise ValueError(f"Unsafe expression node: {type(node).__name__}")


def calculator(expression: str) -> str:
    """Safely evaluate a simple arithmetic expression.

    Args:
        expression: Arithmetic expression over numbers and operators.

    Returns:
        Numeric result converted to string.

    Raises:
        ValueError: If expression is unsafe or invalid.
    """
    _validate_expression(expression)
    value = eval(expression, {"__builtins__": {}}, {})
    return str(value)


def code_executor(code: str) -> str:
    """Execute code in an isolated scope and capture stdout.

    Args:
        code: Python code snippet.

    Returns:
        Captured standard output and locals snapshot.

    Raises:
        RuntimeError: If code execution fails.
    """
    allowed_builtins = {
        "print": print,
        "range": range,
        "len": len,
        "sum": sum,
        "min": min,
        "max": max,
        "sorted": sorted,
    }
    local_scope: Dict[str, Any] = {}
    stream = io.StringIO()
    try:
        with contextlib.redirect_stdout(stream):
            exec(code, {"__builtins__": allowed_builtins}, local_scope)
    except Exception as exc:  # pragma: no cover - sanity guard
        raise RuntimeError(f"code execution failed: {exc}") from exc

    stdout = stream.getvalue().strip()
    locals_view = {k: v for k, v in local_scope.items() if not k.startswith("__")}
    if stdout and locals_view:
        return f"stdout: {stdout}\\nlocals: {locals_view}"
    if stdout:
        return f"stdout: {stdout}"
    return f"locals: {locals_view}"


def run_tool(tool: str, args: Dict[str, Any]) -> ToolResult:
    """Dispatch a tool call to mock implementations.

    Args:
        tool: Tool name.
        args: Tool argument dictionary.

    Returns:
        ToolResult dataclass for executed tool.

    Raises:
        ValueError: If tool name is unknown.
    """
    if tool == "web_search":
        output = web_search(str(args.get("query", "")))
    elif tool == "calculator":
        output = calculator(str(args.get("expression", "")))
    elif tool == "code_executor":
        output = code_executor(str(args.get("code", "")))
    else:
        raise ValueError(f"Unknown tool: {tool}")
    return ToolResult(tool=tool, args=args, output=output)
